### ISSUE TITLE
Automatic reconnect on error

### ISSUE THREAD

**Issue by nielsbasjes** [nielsbasjes/dsmr-tools#3]
```2020-03-22 15:34:42,003 WARN [Timer-Driven Process Thread-2] o.a.n.controller.tasks.ConnectableTask Administratively Yielding FetchSDM630[id=27ee9c83-2fe6-39c0-0000-000000000000] due to uncaught Exception: java.lang.NullPointerException
java.lang.NullPointerException: null
	at com.ghgande.j2mod.modbus.net.SerialConnection.getBaudRate(SerialConnection.java:200)
	at com.ghgande.j2mod.modbus.io.ModbusSerialTransport.getInterFrameDelay(ModbusSerialTransport.java:625)
	at com.ghgande.j2mod.modbus.io.ModbusSerialTransport.waitBetweenFrames(ModbusSerialTransport.java:603)
	at com.ghgande.j2mod.modbus.io.ModbusSerialTransaction.execute(ModbusSerialTransaction.java:136)
	at com.ghgande.j2mod.modbus.facade.AbstractModbusMaster.readInputRegisters(AbstractModbusMaster.java:209)
	at nl.basjes.modbus.ModBusDataReader.read(ModBusDataReader.java:53)
	at nl.basjes.modbus.ModBusDataReader.getRawRegisterBytes(ModBusDataReader.java:173)
	at nl.basjes.energy.sdm630.SDM630Reader.read(SDM630Reader.java:170)
	at nl.basjes.energy.sdm630.SDM630Reader.read(SDM630Reader.java:164)
	at nl.basjes.energy.sdm630.FetchSDM630.onTrigger(FetchSDM630.java:335)
	at org.apache.nifi.processor.AbstractProcessor.onTrigger(AbstractProcessor.java:27)
	at org.apache.nifi.controller.StandardProcessorNode.onTrigger(StandardProcessorNode.java:1165)
	at org.apache.nifi.controller.tasks.ConnectableTask.invoke(ConnectableTask.java:203)
	at org.apache.nifi.controller.scheduling.TimerDrivenSchedulingAgent$1.run(TimerDrivenSchedulingAgent.java:117)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by nielsbasjes** [comment]
Wrong project
